# Automatically build the project

name: Build
on:
  workflow_call:
    input:
      os:
        type: string
        required: true
        default: 'ubuntu-latest'
      java:
        type: string
        required: true
        default: '17'
      artifacts:
        type: boolean
        default: true
    outputs:
      version:
        value: ${{ jobs.build.outputs.version }}

jobs:
  build:
    name: ${{ runner.os }} - JDK ${{ inputs.java }}
    runs-on: ${{ inputs.os }}
    outputs:
      version: ${{ steps.build.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup jdk ${{ inputs.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ inputs.java }}
      - name: Make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: Build
        id: build
        run: ./gradlew build
      - name: Print outputs
        run: echo ${{ steps.build.outputs }}
      - name: Capture build artifacts
        if: ${{ inputs.artifacts }} # Only upload artifacts built from latest java on one OS
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/libs/
