# Automatically build the project

name: Build
on:
  workflow_call:
    inputs:
      os:
        type: string
        required: true
        default: 'ubuntu-latest'
      java:
        type: string
        required: true
        default: '17'
      artifacts:
        type: boolean
        required: true
        default: true
    outputs:
      mod_version:
        value: ${{ jobs.build.outputs.mod_version }}
      archives_base_name:
        value: ${{ jobs.build.outputs.archives_base_name }}
      curseforge_relations:
        value: ${{ jobs.build.outputs.curseforge_relations }}
      curseforge_game_versions:
        value: ${{ jobs.build.outputs.curseforge_game_versions }}
      curseforge_project_id:
        value: ${{ jobs.build.outputs.curseforge_project_id }}

jobs:
  build:
    name: ${{ (startsWith(inputs.os, 'ubuntu') && 'Ubuntu') || (startsWith(inputs.os, 'windows') && 'Windows') || inputs.os }} - JDK ${{ inputs.java }}
    runs-on: ${{ inputs.os }}
    outputs:
      mod_version: ${{ steps.build.outputs.mod_version }}
      archives_base_name: ${{ steps.build.outputs.archives_base_name }}
      curseforge_relations: ${{ steps.build.outputs.curseforge_relations }}
      curseforge_game_versions: ${{ steps.build.outputs.curseforge_game_versions }}
      curseforge_project_id: ${{ steps.build.outputs.curseforge_project_id }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup jdk ${{ inputs.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ inputs.java }}
      - name: Make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: Build
        id: build
        run: ./gradlew setUpGitHubActions build
      - name: Print outputs
        run: echo ${{ toJSON(steps.build.outputs) }}
      - name: Capture build artifacts
        if: ${{ inputs.artifacts }} # Only upload artifacts built from latest java on one OS
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/libs/
